import { describe, expect, it } from "vitest";
import {
  applyContradictionPenalty,
  computeConfidence,
  confidenceCapByTypeCount,
  CONTRADICTION_CAP,
  precisionConfidence,
} from "@/lib/engine/confidenceEngine";
import { PRIOR_SD, posteriorEstimate } from "@/lib/engine/scoreEngine";
import type { EvidenceDirection, EvidenceType } from "@/lib/types/diagnosis";

/** §11 — confidence is the estimate's own error bar, and is deliberately hard to max. */

/** Each item lands in its own turn, i.e. counts as an independent occasion. */
let turnCounter = 0;
function items(
  types: EvidenceType[],
  direction: EvidenceDirection = "positive",
  strength = 0.9,
  reliability = 0.9
) {
  return types.map((type) => ({ type, strength, reliability, direction, turn_id: ++turnCounter }));
}

describe("confidence accumulation", () => {
  it("is zero before any evidence", () => {
    expect(computeConfidence([], []).confidence).toBe(0);
    expect(precisionConfidence(PRIOR_SD)).toBe(0);
  });

  it("rises as evidence arrives", () => {
    const first = computeConfidence(items(["personal_experience"]), []);
    const second = computeConfidence(items(["personal_experience", "decision_example"]), []);
    expect(first.confidence).toBeGreaterThan(0);
    expect(second.confidence).toBeGreaterThan(first.confidence);
  });

  it("stays independent of score: confidence rises on neutral evidence", () => {
    // The same item contributes 0 to the score when its direction is neutral,
    // yet still adds support for the estimate (§1.1).
    const result = computeConfidence(items(["reasoning_pattern"], "neutral"), []);
    expect(result.confidence).toBeGreaterThan(0);
    expect(posteriorEstimate(items(["reasoning_pattern"], "neutral")).score).toBe(50);
  });

  it("tracks the posterior rather than the count of items", () => {
    // Confidence is a function of the error bar, so it must agree with it.
    const evidence = items(["personal_experience", "decision_example", "value_statement"]);
    const { posteriorSd } = posteriorEstimate(evidence);
    expect(computeConfidence(evidence, []).raw).toBeCloseTo(precisionConfidence(posteriorSd), 12);
  });

  it("is order-invariant", () => {
    const evidence = items(
      ["personal_experience", "decision_example", "value_statement", "self_description"],
      "positive"
    );
    const forward = computeConfidence(evidence, []);
    const reversed = computeConfidence([...evidence].reverse(), []);
    expect(reversed.confidence).toBeCloseTo(forward.confidence, 12);
  });
});

describe("diversity cap (§11.2)", () => {
  it("defines the specified ceilings", () => {
    expect(confidenceCapByTypeCount(1)).toBe(0.4);
    expect(confidenceCapByTypeCount(2)).toBe(0.65);
    expect(confidenceCapByTypeCount(3)).toBe(0.85);
    expect(confidenceCapByTypeCount(7)).toBe(1);
  });

  it("caps a pile of same-type evidence at 0.40", () => {
    const thirty = items(Array.from({ length: 30 }, () => "self_description" as EvidenceType), "positive", 1, 1);
    expect(computeConfidence(thirty, []).confidence).toBeCloseTo(0.4, 10);
  });

  it("allows above 0.65 once a third type appears", () => {
    const types: EvidenceType[] = ["self_description", "personal_experience", "decision_example"];
    const thirty = items(
      Array.from({ length: 30 }, (_, i) => types[i % 3]),
      "positive",
      1,
      1
    );
    const result = computeConfidence(thirty, []);
    expect(result.confidence).toBeGreaterThan(0.65);
    expect(result.confidence).toBeLessThanOrEqual(0.85);
  });

  it("reports which ceiling applied", () => {
    expect(computeConfidence(items(["self_description"]), []).cap).toBe(0.4);
    expect(computeConfidence(items(["self_description", "value_statement"]), []).cap).toBe(0.65);
  });
});

describe("contradiction penalty (§11.3)", () => {
  it("reduces confidence for unresolved contradictions only", () => {
    const base = 0.8;
    const unresolved = applyContradictionPenalty(base, [{ kind: "semantic" as const, severity: 0.8, status: "unresolved" }]);
    const resolved = applyContradictionPenalty(base, [{ kind: "semantic" as const, severity: 0.8, status: "resolved" }]);

    expect(unresolved).toBeCloseTo(0.8 * (1 - 0.25 * 0.8), 5);
    expect(resolved).toBe(base);
  });

  it("compounds across multiple contradictions", () => {
    const one = applyContradictionPenalty(1, [{ kind: "semantic" as const, severity: 1, status: "unresolved" }]);
    const two = applyContradictionPenalty(1, [
      { kind: "semantic" as const, severity: 1, status: "unresolved" },
      { kind: "semantic" as const, severity: 1, status: "unresolved" },
    ]);
    expect(two).toBeLessThan(one);
  });

  it("stops compounding past the cap", () => {
    // Contradictions are generated by pairing every positive item against every
    // negative one, so their count grows with the product. Without a cap, an
    // element with plenty of mixed evidence had its confidence driven to zero
    // and could never satisfy the conf ≥ 0.75 exit condition.
    const many = Array.from({ length: 120 }, () => ({ kind: "semantic" as const, severity: 1, status: "unresolved" as const }));
    const capped = applyContradictionPenalty(1, many);
    const exactlyCap = applyContradictionPenalty(
      1,
      Array.from({ length: CONTRADICTION_CAP }, () => ({ kind: "semantic" as const, severity: 1, status: "unresolved" as const }))
    );

    expect(capped).toBeCloseTo(exactlyCap, 12);
    expect(capped).toBeGreaterThan(0.4);
  });

  it("applies the most severe contradictions first", () => {
    const mild = { kind: "semantic" as const, severity: 0.1, status: "unresolved" as const };
    const severe = { kind: "semantic" as const, severity: 1, status: "unresolved" as const };
    const withSevere = applyContradictionPenalty(1, [mild, mild, mild, severe]);
    const mildOnly = applyContradictionPenalty(1, [mild, mild, mild]);
    expect(withSevere).toBeLessThan(mildOnly);
  });

  it("restores confidence when the contradiction is resolved", () => {
    const evidence = items(["personal_experience", "decision_example"]);
    const penalised = computeConfidence(evidence, [{ kind: "semantic" as const, severity: 0.9, status: "unresolved" }]);
    const restored = computeConfidence(evidence, [{ kind: "semantic" as const, severity: 0.9, status: "resolved" }]);

    expect(restored.confidence).toBeGreaterThan(penalised.confidence);
    // Recomputation is the only path, so a lifted discount leaves no residue.
    expect(restored.confidence).toBeCloseTo(computeConfidence(evidence, []).confidence, 12);
  });

  it("does not discount twice for a directional clash", () => {
    // A directional contradiction is opposing evidence on one element, which the
    // posterior has already priced in. Charging for it again was what drove
    // confidence to zero on any element with a mixed history.
    const evidence = items(["personal_experience", "decision_example", "value_statement"]);
    const clean = computeConfidence(evidence, []);
    const withDirectional = computeConfidence(
      evidence,
      Array.from({ length: 50 }, () => ({
        kind: "directional" as const,
        severity: 1,
        status: "unresolved" as const,
      }))
    );
    expect(withDirectional.confidence).toBeCloseTo(clean.confidence, 12);
  });

  it("still discounts for a semantic conflict", () => {
    // A conflict between two *different* elements is invisible to the per-element
    // posterior, so this is the case the discount exists for.
    const evidence = items(["personal_experience", "decision_example", "value_statement"]);
    const clean = computeConfidence(evidence, []);
    const withSemantic = computeConfidence(evidence, [
      { kind: "semantic", severity: 0.8, status: "unresolved" },
    ]);
    expect(withSemantic.confidence).toBeLessThan(clean.confidence);
  });

  it("keeps mixed evidence uncertain even without recorded contradictions", () => {
    // The posterior does this on its own: evidence pointing both ways lands the
    // rate near 0.5, which is where its variance is highest.
    const consistent = items(["personal_experience", "decision_example", "value_statement"], "positive", 1, 1);
    const mixed = [
      ...items(["personal_experience"], "positive", 1, 1),
      ...items(["decision_example"], "negative", 1, 1),
      ...items(["value_statement"], "positive", 1, 1),
    ];
    expect(computeConfidence(mixed, []).confidence).toBeLessThan(
      computeConfidence(consistent, []).confidence
    );
  });
});
